spring:
    application:
        name: Api-Gateway

    # main:
    #     web-application-type: reactive
    
    cloud:
        gateway:
            routes:
              - id: path_route
                uri: http://192.168.1.9:8081
                predicates:
                  - Path= /api/users/{segment}
        
              - id: path_route
                uri: http://192.168.1.9:8082
                predicates:
                  - Path= /api/hotels/{segment}

              - id: path_route
                uri: http://192.168.1.9:8083
                predicates:
                  - Path= /api/ratings/{segment}

                  
server:
    port: 8084


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    regiser-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
